name: 'Docker Build and Push'
description: 'Build and push Docker image to container registry'
author: 'Simplify9'

inputs:
  registry:
    description: 'Container registry URL (e.g., docker.io, registry.digitalocean.com, myregistry.azurecr.io)'
    required: false
    default: 'docker.io'
  image-name:
    description: 'Docker image name (e.g., simplify9/sw-surl-api, my-app)'
    required: true
  version:
    description: 'Version tag for the Docker image'
    required: true
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password or token'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: './Dockerfile'
  context:
    description: 'Docker build context'
    required: false
    default: '.'
  platforms:
    description: 'Target platforms for build'
    required: false
    default: 'linux/amd64'
  push:
    description: 'Push image to registry'
    required: false
    default: 'true'
  cache:
    description: 'Enable build cache'
    required: false
    default: 'true'

outputs:
  image-tags:
    description: 'Generated image tags'
    value: ${{ steps.meta.outputs.tags }}
  image-digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.platforms }}

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry != 'docker.io' && inputs.registry || '' }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.registry != 'docker.io' && format('{0}/{1}', inputs.registry, inputs.image-name) || inputs.image-name }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ inputs.version }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
        cache-from: ${{ inputs.cache == 'true' && 'type=gha' || '' }}
        cache-to: ${{ inputs.cache == 'true' && 'type=gha,mode=max' || '' }}

    - name: Output image information
      shell: bash
      run: |
        echo "### 🐳 Docker Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Registry:** ${{ inputs.registry }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Image:** ${{ inputs.image-name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Version:** ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Platforms:** ${{ inputs.platforms }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Tags:**" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.meta.outputs.tags }}" | sed 's/^/  - /' >> $GITHUB_STEP_SUMMARY
        echo "- **Digest:** ${{ steps.build.outputs.digest }}" >> $GITHUB_STEP_SUMMARY